### ISSUE TITLE
415 Unsupported Media Type

### ISSUE THREAD

**Issue by xiaobopang** [bianjieai/ddc-sdk-go#30]
[ERROR] 2022/06/08 09:42:14 block.go:34: failed to execute GetBlockByNumber: 415 Unsupported Media Type: {"message":"Non-gRPC request matched gRPC route"}

按照文档调用接口,出现这个错误,是需要在那里配置请求方式么?

**Comment by MaricoHan** [comment]
> [ERROR] 2022/06/08 09:42:14 block.go:34: failed to execute GetBlockByNumber: 415 Unsupported Media Type: {"message":"Non-gRPC request matched gRPC route"}
> 
> 按照文档调用接口,出现这个错误,是需要在那里配置请求方式么?

访问的链接不是grpc端口吧

**Comment by xiaobopang** [comment]
已解决,谢谢~
